# To prevent github push events from triggering builds, set pipeline
# github settings to "Filter builds using a conditional" with:
#     build.pull_request.base_branch == "master"
# (https://buildkite.com/stanford-aha/aha-submod-flow/settings/repository)

steps:
- label: ":pipeline:"
  agents: { docker: true }
  plugins:
      # Turn off normal/slow repo+submods checkout b/c all we need is pipeline.yml
      - uber-workflow/run-without-clone:
  commands:
  - 'echo "+++ Must have (empty!) working directory"; set -x;
     d=$$BUILDKITE_BUILD_CHECKOUT_PATH;
     /bin/rm -rf $$d; mkdir -p $$d; ls -ld $$d; cd $$d'
  
  # Note, /home/buildkite-agent/bin/status-update must exist on agent machine
  # Also see ~steveri/bin/status-update on kiwi
  - 'echo "+++ Notify github of pending status";
     ~/bin/status-update --force pending'
  
  - 'echo "--- CUSTOM CHECKOUT BEGIN"; set -x;
     aha_clone=$$BUILDKITE_BUILD_CHECKOUT_PATH;
     git clone https://github.com/StanfordAHA/aha $$aha_clone; cd $$aha_clone;

     echo "Set BPPR_TAIL for later usage, e.g. BPPR_TAIL=canal";
     export BPPR_TAIL=`echo "$BUILDKITE_PULL_REQUEST_REPO" | sed "s/.git\$//"` || echo fail;
     BPPR_TAIL=`echo "$$BPPR_TAIL" | sed "s,http.*github.com/.*/,,"` || echo fail;
       
     echo "Trigger aha-flow pipeline";
     buildkite-agent pipeline upload .buildkite/pr_trigger.yml;'
  - echo "--- CUSTOM CHECKOUT END"

