# This is a copy of the online buildkite steps for the aha-flow pipeline,
# see https://buildkite.com/stanford-aha/aha-flow/settings/steps

# Last update Sep 2024

env:
  DEV_BRANCH: master
  # DEV_BRANCH: ci-cleanup
  AHA_REPO: https://raw.githubusercontent.com/StanfordAHA/aha
  STEPSCRIPT: .buildkite/bin/custom-checkout.sh

# Must do commands in pre-checkout else get wrong BUILDKITE_MESSAGE
steps:
- label: ":pipeline:"
  agents: { docker: true }
  plugins:
  - uber-workflow/run-without-clone:
  - improbable-eng/metahook:
      pre-checkout: |
        # (pwd; ls -l) || echo okay
        udev=$$AHA_REPO/$$DEV_BRANCH/$$STEPSCRIPT
        httpcode=`curl $$udev -o custom-checkout.sh -w '%{http_code}'`
        if ! [ "$$httpcode" == 200 ]; then
            echo "Cannot find steps in branch '$$DEV_BRANCH'; trying master instead"
            curl $$AHA_REPO/master/$$STEPSCRIPT -o custom-checkout.sh
        fi
        source custom-checkout.sh --aha-flow
  command: echo DONE  # (Breaks if no command)
