################################################################################
# This is a copy of the online buildkite steps for the aha-submod-flow pipeline,
# see https://buildkite.com/stanford-aha/aha-submod-flow/settings/steps
# 
# Last update Sep 2024
################################################################################
# To prevent github push events from triggering builds, set pipeline
# github settings to "Filter builds using a conditional" with:
#     build.pull_request.base_branch == "master"
# (https://buildkite.com/stanford-aha/aha-submod-flow/settings/repository)

env:
  DEV_BRANCH: master
  # DEV_BRANCH: ci-cleanup
  AHA_REPO: https://raw.githubusercontent.com/StanfordAHA/aha
  STEPSCRIPT: .buildkite/bin/custom-checkout.sh

steps:
- label: ":pipeline:"
  agents: { docker: true }
  command: echo "--- DONE"
  plugins:
    # Turn off normal/slow repo+submods checkout b/c all we need is pipeline.yml
    - uber-workflow/run-without-clone:
      
    # My hooks
    - improbable-eng/metahook:
        pre-checkout: |
          set -x
          echo FOO DEBUGGO
          udev=$$AHA_REPO/$$DEV_BRANCH/$$STEPSCRIPT
          httpcode=`curl $$udev -o custom-checkout.sh -w '%{http_code}'`
          if ! [ "$$httpcode" == 200 ]; then
              echo "Cannot find steps in branch '$$DEV_BRANCH'; trying master instead"
              curl $$AHA_REPO/master/$$STEPSCRIPT -o custom-checkout.sh
          fi
          source custom-checkout.sh --aha-submod-flow
          exit
