# To turn daemon on or off, search code below and change to one of:
#   aha regress $$CONFIG --daemon auto  # Use daemon
#   aha regress $$CONFIG                # No daemon

env:
  CONFIG: ${CONFIG:-daily}

steps:

- label: ":wrench: Build Docker Image"
  key: "docker-build"
  plugins:
  # Override standard checkout procedure with custom checkout script
  - uber-workflow/run-without-clone:

  # My hooks
  - improbable-eng/metahook:

      # Clone aha repo and optionally update submod according to where build request originated:
      # Req from aha repo:    check out aha commit BUILDKITE_COMMIT
      # Req from submod repo: check out aha master branch, update submod w BUILDKITE_COMMIT
      pre-checkout: |
        echo "+++ BDI PRE CHECKOUT HOOK"
        set +u     # nounset? not on my watch!

        if [ "$$FLOW_HEAD_SHA" ]; then
            echo "+++ ERROR Not processing heroku requests anymore"; exit 13; fi

        # Clone the aha repo; starting in root dir '/' I think
        echo I am in dir `pwd`
        aha_clone=$BUILDKITE_BUILD_CHECKOUT_PATH;
        set -x
        /bin/rm -rf $$aha_clone; mkdir -p $$aha_clone
        git clone https://github.com/StanfordAHA/aha $$aha_clone; cd $$aha_clone;
        git remote set-url origin https://github.com/StanfordAHA/aha     # Why?
        git clean -ffxdq
        set +x
        bin=$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin

        # Make sure env var BUILDKITE_PULL_REQUEST_REPO is set correctly
        source $$bin/update-pr-repo.sh

        # If build was triggered by a pull request, annotate build with
        #    links pointing to pull request on github.
        # Set REQUEST_TYPE to one of "AHA_PUSH", "AHA_PR", or "SUBMOD_PR"
        # Set PR_REPO_TAIL to submod associated with the PR, e.g. "canal"
        # Add REQUEST_TYPE env temp file for use by later steps
        source $$bin/set-trigfrom-and-reqtype.sh

        ~/bin/status-update --force pending   # Send "pending" status to github PR page

        # Checkout and update correct aha branch and submodules
        source $$bin/custom-checkout.sh

      # Send regression test pass-fail info to github pull request page
      pre-exit: |
        echo "+++ CHECKING EXIT STATUS"; set -x
        echo "Send status to github, delete docker image if job failed"

        # status-update exit status will tell us if this step has failed
        if ! ~/bin/status-update pending; then
            # Build failed already, remove the docker image and begone
            (set -x; docker image rm "garnet:aha-flow-build-$${BUILDKITE_BUILD_NUMBER}" --no-prune)
        fi

  commands:
  - echo "+++ BDI PIPELINE.XML COMMANDS BEGIN"

  - echo "--- DEBUG DOCKER TRASH"
  - set -x; docker images; docker ps;

  - echo "--- Creating garnet Image"
  - docker build . -t "garnet:aha-flow-build-${BUILDKITE_BUILD_NUMBER}"

  - echo "--- Pruning Docker Images"
  - yes | docker image prune -a --filter "until=6h" --filter=label='description=garnet' || true

  - echo "--- BDI PIPELINE.XML COMMANDS END"

  agents:
    docker: true

- label: ":hammer: Amber Gold RTL 1m"
  key: "goldcheck-amber"
  depends_on: "docker-build"
  # Set soft_fail so that failing gold check does not fail pipeline.
  soft_fail: true
  commands:
    - set -x; /aha/aha/bin/rtl-goldcheck.sh amber
  plugins:
    - uber-workflow/run-without-clone:
    - docker#v3.2.0:
        image: garnet:aha-flow-build-${BUILDKITE_BUILD_NUMBER}
        volumes:
          - "/cad/:/cad"
        mount-checkout: false
        propagate-environment: true
        environment:
          - CONFIG
          - FLOW_REPO
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true

- label: ":hammer: Onyx Gold RTL 1m"
  key: "goldcheck-onyx"
  depends_on: "docker-build"
  # Set soft_fail so that failing gold check does not fail pipeline.
  soft_fail: true
  commands:
    - set -x; /aha/aha/bin/rtl-goldcheck.sh onyx
  plugins:
    - uber-workflow/run-without-clone:
    - docker#v3.2.0:
        volumes:
          - "/cad/:/cad"
        mount-checkout: false
        propagate-environment: true
        environment:
          - CONFIG
          - FLOW_REPO
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true

- wait: { continue_on_failure: true } # One step at a time + continue on failure

- label: ":skull_and_crossbones: Delete Docker Image"
  # Set soft_fail so that failing cleanup does not fail pipeline.
  soft_fail: true
  depends_on:
  - "integration-tests"
  - "goldcheck-amber"
  - "goldcheck-onyx"
  commands:
  # '--no-prune' so it doesn't prune dangling images, we want to use them for the Docker cache.
  - docker image rm "garnet:aha-flow-build-${BUILDKITE_BUILD_NUMBER}" --no-prune
  agents:
    docker: true
  plugins:
  - uber-workflow/run-without-clone:
