env:
  CONFIG: ${CONFIG:-daily}

steps:

- label: ":wrench: Build Docker Image"
  key: "docker-build"
  plugins:
  # Override standard checkout procedure with custom checkout script
  - uber-workflow/run-without-clone:

  commands:
  - echo hello world; exit 0

  agents:
    docker: true

# ------------------------------------------------------------------------
- label: ":hammer: Amber Gold RTL 1m"
  key: "goldcheck-amber"
  depends_on: "docker-build"
  # Set soft_fail so that failing gold check does not fail pipeline.
  soft_fail: true
  commands:
    - set -x; /aha/aha/bin/rtl-goldcheck.sh amber
  plugins:
    - uber-workflow/run-without-clone:
    - docker#v3.2.0:
        image: garnet:latest
        volumes:
          - "/cad/:/cad"
        mount-checkout: false
        propagate-environment: true
        environment:
          - CONFIG
          - FLOW_REPO
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true

# ------------------------------------------------------------------------
- label: ":hammer: Onyx Gold RTL 1m"
  key: "goldcheck-onyx"
  depends_on: "docker-build"
  # Set soft_fail so that failing gold check does not fail pipeline.
  soft_fail: true
  commands:
    - set -x; /aha/aha/bin/rtl-goldcheck.sh onyx
  plugins:
    - uber-workflow/run-without-clone:
    - docker#v3.2.0:
        image: garnet:latest
        volumes:
          - "/cad/:/cad"
        mount-checkout: false
        propagate-environment: true
        environment:
          - CONFIG
          - FLOW_REPO
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true

# ------------------------------------------------------------------------
- label: ":hammer: Onyx Integration Tests"
  key: "integration-tests"
  depends_on: "docker-build"

  plugins:
    - uber-workflow/run-without-clone:
  commands:
  - hello world; exit 0

  agents:
    docker: true

- wait: { continue_on_failure: true } # One step at a time + continue on failure

- label: ":skull_and_crossbones: Delete Docker Image"
  # Set soft_fail so that failing cleanup does not fail pipeline.
  soft_fail: true
  depends_on:
  - "integration-tests"
  - "goldcheck-amber"
  - "goldcheck-onyx"
  commands:
  - echo hello world; exit 0
  agents:
    docker: true
  plugins:
  - uber-workflow/run-without-clone:
