env:
  TEST1: "BAR"
  
steps:
- label: ":wrench: Build Docker Image"
  key: "docker-build"
  commands:
  - export TEST1=FOO
  - export TEST2=FOO
  - echo "--- Creating garnet Image"
  - docker build . -t "garnet:$BUILDKITE_COMMIT"
  - echo "--- Pruning Docker Images"
  - yes | docker image prune -a --filter "until=24h" --filter=label='description=garnet'
  agents:
    docker: true
  
- label: ":hammer: Integration Tests"
  key: "integration-tests"
  depends_on: "docker-build"
  commands:
  - echo $$TEST1
  - echo $$TEST2
  - source /cad/modules/tcl/init/sh
  - module load base incisive
  - ls /aha
  - aha garnet --width 16 --height 16 --verilog --interconnect-only
  - aha halide tests/conv_1_2
  - aha map tests/conv_1_2 --width 16 --height 16
  - aha test tests/conv_1_2
  # We need to clean out the docker workdir because files in docker 
  # have root permissions, and the workdir is a mapped volume so
  # the next buildkite job in that directory will fail because it
  # couldn't remove the existing files.
  - rm -rf /aha/*
  plugins:
    - docker#v3.2.0:
        image: garnet:$BUILDKITE_COMMIT
        volumes:
          - "/cad/:/cad"
        mount-checkout: false
        propagate-environment: true
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true

# - label: "Delete Docker Image"
#   depends_on: "integration-tests"
#   commands:
#   # --no-prune so it doesn't prune dangling images, we want to use them for the Docker cache.
#   - docker image rm "garnet" --no-prune
