env:
  CONFIG: daily

steps:
- label: ":wrench: Build Docker Image"
  key: "docker-build"
  commands:
  - echo "--- Handle PR"
  - if [[ $$FLOW_REPO ]]; then (
      cd $FLOW_REPO && git fetch && git checkout $FLOW_HEAD_SHA;
    ) fi
  - echo "--- Creating garnet Image"
  - docker build . -t "garnet:$BUILDKITE_COMMIT$FLOW_REPO$FLOW_HEAD_SHA"
  - echo "--- Pruning Docker Images"
  - yes | docker image prune -a --filter "until=6h" --filter=label='description=garnet'
  agents:
    docker: true
  
- label: ":hammer: Integration Tests"
  key: "integration-tests"
  depends_on: "docker-build"
  commands:
  - source /aha/bin/activate
  - source /cad/modules/tcl/init/sh
  - module load base incisive
  - ls /aha
  # Run regression tests
  - if [[ $$FLOW_REPO ]]; then (
      export CONFIG=pr;
    ) fi
  - aha regress $$CONFIG
  # We report success to the aha-flow app by removing the .TEMP file,
  # which is created in the post-checkout hook and checked for in the
  # pre-exit hook.
  - echo "--- Removing Failure Canary"
  - ls -al /buildkite
  - rm -rf /buildkite/.TEST
  - ls -al /buildkite
  plugins:
    - docker#v3.2.0:
        image: garnet:$BUILDKITE_COMMIT$FLOW_REPO$FLOW_HEAD_SHA
        volumes:
          - "/cad/:/cad"
          - "./temp:/buildkite:rw"
        mount-checkout: false
        propagate-environment: true
        environment:
          - CONFIG
          - FLOW_REPO
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true

- label: ":skull_and_crossbones: Delete Docker Image"
  depends_on: "integration-tests"
  commands:
  # '--no-prune' so it doesn't prune dangling images, we want to use
  # them for the Docker cache.
  - docker image rm "garnet:$BUILDKITE_COMMIT$FLOW_REPO$FLOW_HEAD_SHA" --no-prune
  agents:
    docker: true
